server:
  port: 1235

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  #微服务跨域访问
  instance:
    prefer-ip-address: true
spring:
  application:
    name: cuerry
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lkk_trip
    username: root
    password: root123456
  redis:
    host: 127.0.0.1
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#MyBatis配置
mybatis:
  type-aliases-package: com.gedu.domain
  configuration:
    map-underscore-to-camel-case: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml



